### ISSUE TITLE
Download filename not showing up

### ISSUE THREAD

**Issue by kyteinsky** [AdityaKG-169/FileTransfer#1]
# When I open the URL where download is to be found, I get no filename or extension there, please make provision for that in you js code

Thanks

**Comment by akgsh** [comment]
Can you please add the screenshot of the problem? According to me, the functionality should be like:

- You choose a file
- You Get a Link (Example: 192.168.1.9:4700) 
- You open this link and your file automatically gets downloaded

If this is not what you are getting please attach the screenshot.
